refactor: tidy up rust install logic

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -174,9 +174,17 @@ install_thefuck() {
 }
 
 install_rust() {
-    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+    
+    if ! command -v rustc >/dev/null 2>&1; then
+        echo "Installing rust"
+        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+    fi
 
-    source "$HOME/.cargo/env"
+    if [ -f "$HOME/.cargo/env" ]; then
+       source "$HOME/.cargo/env"
+    else
+        echo "Error: $HOME/.cargo/env not found."
+    fi
 
     # Install some rust tools
     for tool in "${cargo_list[@]}"; do
